test

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,23 +1,15 @@
-echo `pwd`
-echo
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir> <env-dir>
 
-echo `ls`
-echo
+### Configure environment
 
-echo BUILD_DIR $BUILD_DIR
-echo
+set -o errexit    # always exit on error
 
-echo CACHE_DIR $CACHE_DIR
-echo
+### Configure directories
 
-echo ENV_DIR $ENV_DIR
-echo
-
-echo `ls $ENV_DIR`
-echo
-
-echo BP_DIR $BP_DIR
-echo
+BUILD_DIR=${1:-}
+CACHE_DIR=${2:-}
+ENV_DIR=${3:-}
 
 cd $BUILD_DIR
 yarn workspace seneque-ui run build -e production
